# Generated by Django 6.0 on 2025-12-25 22:43

from django.db import migrations


def create_roles(apps, schema_editor):
    Role = apps.get_model('main', 'Role')

    # Create roles with their permissions
    roles_data = [
        {
            'name': 'SuperAdmin',
            'description': 'Super Administrator with all permissions',
            'permissions': {
                'all': True,  # Special permission for all access
                'manage_users': True,
                'manage_roles': True,
                'manage_system': True,
                'view_reports': True,
                'manage_deliveries': True,
                'manage_customers': True,
                'manage_riders': True,
            }
        },
        {
            'name': 'Admin',
            'description': 'Administrator with assigned permissions',
            'permissions': {
                'manage_users': True,
                'manage_roles': False,
                'manage_system': False,
                'view_reports': True,
                'manage_deliveries': True,
                'manage_customers': True,
                'manage_riders': True,
            }
        },
        {
            'name': 'customer',
            'description': 'Customer role for end users',
            'permissions': {
                'create_orders': True,
                'view_own_orders': True,
                'track_orders': True,
                'manage_profile': True,
            }
        },
        {
            'name': 'rider',
            'description': 'Rider role for delivery personnel',
            'permissions': {
                'accept_deliveries': True,
                'update_delivery_status': True,
                'view_assigned_deliveries': True,
                'manage_profile': True,
                'view_earnings': True,
            }
        },
    ]

    for role_data in roles_data:
        Role.objects.create(**role_data)


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_roles),
    ]
